version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsw
      MYSQL_USER: dsw-backend
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - C:/path/to/mysql-data:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
